text: [
{"AED: "United Arab Emirates Dirham"},
{text: "AFN", value: "AFN:Afghan Afghani"},
{text: "ALL", value: "ALL:Albanian Lek"},
{text: "AMD", value: "AMD:Armenian Dram"},
{text: "ANG", value: "ANG:Netherlands Antillean Guilder"},
{text: "AOA", value: "AOA:Angolan Kwanza"},
{text: "ARS", value: "ARS:Argentine Peso"},
{text: "AUD", value: "AUD:Australian Dollar"},
{text: "AWG", value: "AWG:Aruban Florin"},
{text: "AZN", value: "AZN:Azerbaijani Manat"},
{text: "BAM", value: "BAM:Bosnia-Herzegovina Convertible Mark,"}
{text: "BBD", value: "BBD:Barbadian Dollar"},
{text: "BDT", value: "BDT:Bangladeshi Taka"},
{text: "BGN", value: "BGN:Bulgarian Lev"},
{text: "BHD", value: "BHD:Bahraini Dinar"},
{text: "BIF", value: "BIF:Burundian Franc"},
{text: "BMD", value: "BMD:Bermudan Dollar"},
{text: "BND", value: "BND:Brunei Dollar"},
{text: "BOB", value: "BOB:Bolivian Boliviano"},
{text: "BRL", value: "BRL:Brazilian Real"},
{text: "BSD", value: "BSD:Bahamian Dollar"},
{text: "BTC", value: "BTC:Bitcoin"},
{text: "BTN", value: "BTN:Bhutanese Ngultrum"},
{text: "BWP", value: "BWP:Botswanan Pula"},
{text: "BYN", value: "BYN:Belarusian Ruble"},
{text: "BZD", value: "BZD:Belize Dollar"},
{text: "CAD", value: "CAD:Canadian Dollar"},
{text: "CDF", value: "CDF:Congolese Franc"},
{text: "CHF", value: "CHF:Swiss Franc"},
{text: "CLF", value: "CLF:Chilean Unit of Account (UF)"},
{text: "CLP", value: "CLP:Chilean Peso"},
{text: "CNH", value: "CNH:Chinese Yuan (Offshore)"},
{text: "CNY", value: "CNY:Chinese Yuan"},
{text: "COP", value: "COP:Colombian Peso"},
{text: "CRC", value: "CRC:Costa Rican Colón"},
{text: "CUC", value: "CUC:Cuban Convertible Peso"},
{text: "CUP", value: "CUP:Cuban Peso"},
{text: "CVE", value: "CVE:Cape Verdean Escudo"},
{text: "CZK", value: "CZK:Czech Republic Koruna"},
{text: "DJF", value: "DJF:Djiboutian Franc"},
{text: "DKK", value: "DKK:Danish Krone"},
{text: "DOP", value: "DOP:Dominican Peso"},
{text: "DZD", value: "DZD:Algerian Dinar"},
{text: "EGP", value: "EGP:Egyptian Pound"},
{text: "ERN", value: "ERN:Eritrean Nakfa"},
{text: "ETB", value: "ETB:Ethiopian Birr"},
{text: "EUR", value: "EUR:Euro"},
{text: "FJD", value: "FJD:Fijian Dollar"},
{text: "FKP", value: "FKP:Falkland Islands Pound"},
{text: "GBP", value: "GBP:British Pound Sterling"},
{text: "GEL", value: "GEL:Georgian Lari"},
{text: "GGP", value: "GGP:Guernsey Pound"},
{text: "GHS", value: "GHS:Ghanaian Cedi"},
{text: "GIP", value: "GIP:Gibraltar Pound"},
{text: "GMD", value: "GMD:Gambian Dalasi"},
{text: "GNF", value: "GNF:Guinean Franc"},
{text: "GTQ", value: "GTQ:Guatemalan Quetzal"},
{text: "GYD", value: "GYD:Guyanaese Dollar"},
{text: "HKD", value: "HKD:Hong Kong Dollar"},
{text: "HNL", value: "HNL:Honduran Lempira"},
{text: "HRK", value: "HRK:Croatian Kuna"},
{text: "HTG", value: "HTG:Haitian Gourde"},
{text: "HUF", value: "HUF:Hungarian Forint"},
{text: "IDR", value: "IDR:Indonesian Rupiah"},
{text: "ILS", value: "ILS:Israeli New Sheqel"},
{text: "IMP", value: "IMP:Manx pound"},
{text: "INR", value: "INR:Indian Rupee"},
{text: "IQD", value: "IQD:Iraqi Dinar"},
{text: "IRR", value: "IRR:Iranian Rial"},
{text: "ISK", value: "ISK:Icelandic Króna"},
{text: "JEP", value: "JEP:Jersey Pound"},
{text: "JMD", value: "JMD:Jamaican Dollar"},
{text: "JOD", value: "JOD:Jordanian Dinar"},
{text: "JPY", value: "JPY:Japanese Yen"},
{text: "KES", value: "KES:Kenyan Shilling"},
{text: "KGS", value: "KGS:Kyrgystani Som"},
{text: "KHR", value: "KHR:Cambodian Riel"},
{text: "KMF", value: "KMF:Comorian Franc"},
{text: "KPW", value: "KPW:North Korean Won"},
{text: "KRW", value: "KRW:South Korean Won"},
{text: "KWD", value: "KWD:Kuwaiti Dinar"},
{text: "KYD", value: "KYD:Cayman Islands Dollar"},
{text: "KZT", value: "KZT:Kazakhstani Tenge"},
{text: "LAK", value: "LAK:Laotian Kip"},
{text: "LBP", value: "LBP:Lebanese Pound"},
{text: "LKR", value: "LKR:Sri Lankan Rupee"},
{text: "LRD", value: "LRD:Liberian Dollar"},
{text: "LSL", value: "LSL:Lesotho Loti"},
{text: "LYD", value: "LYD:Libyan Dinar"},
{text: "MAD", value: "MAD:Moroccan Dirham"},
{text: "MDL", value: "MDL:Moldovan Leu"},
{text: "MGA", value: "MGA:Malagasy Ariary"},
{text: "MKD", value: "MKD:Macedonian Denar"},
{text: "MMK", value: "MMK:Myanma Kyat"},
{text: "MNT", value: "MNT:Mongolian Tugrik"},
{text: "MOP", value: "MOP:Macanese Pataca"},
{text: "MRO", value: "MRO:Mauritanian Ouguiya (pre-2018)"},
{text: "MRU", value: "MRU:Mauritanian Ouguiya"},
{text: "MUR", value: "MUR:Mauritian Rupee"},
{text: "MVR", value: "MVR:Maldivian Rufiyaa"},
{text: "MWK", value: "MWK:Malawian Kwacha"},
{text: "MXN", value: "MXN:Mexican Peso"},
{text: "MYR", value: "MYR:Malaysian Ringgit"},
{text: "MZN", value: "MZN:Mozambican Metical"},
{text: "NAD", value: "NAD:Namibian Dollar"},
{text: "NGN", value: "NGN:Nigerian Naira"},
{text: "NIO", value: "NIO:Nicaraguan Córdoba"},
{text: "NOK", value: "NOK:Norwegian Krone"},
{text: "NPR", value: "NPR:Nepalese Rupee"},
{text: "NZD", value: "NZD:New Zealand Dollar"},
{text: "OMR", value: "OMR:Omani Rial"},
{text: "PAB", value: "PAB:Panamanian Balboa"},
{text: "PEN", value: "PEN:Peruvian Nuevo Sol"},
{text: "PGK", value: "PGK:Papua New Guinean Kina"},
{text: "PHP", value: "PHP:Philippine Peso"},
{text: "PKR", value: "PKR:Pakistani Rupee"},
{text: "PLN", value: "PLN:Polish Zloty"},
{text: "PYG", value: "PYG:Paraguayan Guarani"},
{text: "QAR", value: "QAR:Qatari Rial"},
{text: "RON", value: "RON:Romanian Leu"},
{text: "RSD", value: "RSD:Serbian Dinar"},
{text: "RUB", value: "RUB:Russian Ruble"},
{text: "RWF", value: "RWF:Rwandan Franc"},
{text: "SAR", value: "SAR:Saudi Riyal"},
{text: "SBD", value: "SBD:Solomon Islands Dollar"},
{text: "SCR", value: "SCR:Seychellois Rupee"},
{text: "SDG", value: "SDG:Sudanese Pound"},
{text: "SEK", value: "SEK:Swedish Krona"},
{text: "SGD", value: "SGD:Singapore Dollar"},
{text: "SHP", value: "SHP:Saint Helena Pound"},
{text: "SLL", value: "SLL:Sierra Leonean Leone"},
{text: "SOS", value: "SOS:Somali Shilling"},
{text: "SRD", value: "SRD:Surinamese Dollar"},
{text: "SSP", value: "SSP:South Sudanese Pound"},
{text: "STD", value: "STD:São Tomé and Príncipe Dobra (pre-20,18)"}
{text: "STN", value: "STN:São Tomé and Príncipe Dobra"},
{text: "SVC", value: "SVC:Salvadoran Colón"},
{text: "SYP", value: "SYP:Syrian Pound"},
{text: "SZL", value: "SZL:Swazi Lilangeni"},
{text: "THB", value: "THB:Thai Baht"},
{text: "TJS", value: "TJS:Tajikistani Somoni"},
{text: "TMT", value: "TMT:Turkmenistani Manat"},
{text: "TND", value: "TND:Tunisian Dinar"},
{text: "TOP", value: "TOP:Tongan Pa'anga"},
{text: "TRY", value: "TRY:Turkish Lira"},
{text: "TTD", value: "TTD:Trinidad and Tobago Dollar"},
{text: "TWD", value: "TWD:New Taiwan Dollar"},
{text: "TZS", value: "TZS:Tanzanian Shilling"},
{text: "UAH", value: "UAH:Ukrainian Hryvnia"},
{text: "UGX", value: "UGX:Ugandan Shilling"},
{text: "USD", value: "USD:United States Dollar"},
{text: "UYU", value: "UYU:Uruguayan Peso"},
{text: "UZS", value: "UZS:Uzbekistan Som"},
{text: "VEF", value: "VEF:Venezuelan Bolívar Fuerte (Old)"},
{text: "VES", value: "VES:Venezuelan Bolívar Soberano"},
{text: "VND", value: "VND:Vietnamese Dong"},
{text: "VUV", value: "VUV:Vanuatu Vatu"},
{text: "WST", value: "WST:Samoan Tala"},
{text: "XAF", value: "XAF:CFA Franc BEAC"},
{text: "XAG", value: "XAG:Silver Ounce"},
{text: "XAU", value: "XAU:Gold Ounce"},
{text: "XCD", value: "XCD:East Caribbean Dollar"},
{text: "XDR", value: "XDR:Special Drawing Rights"},
{text: "XOF", value: "XOF:CFA Franc BCEAO"},
{text: "XPD", value: "XPD:Palladium Ounce"},
{text: "XPF", value: "XPF:CFP Franc"},
{text: "XPT", value: "XPT:Platinum Ounce"},
{text: "YER", value: "YER:Yemeni Rial"},
{text: "ZAR", value: "ZAR:South African Rand"},
{text: "ZMW", value: "ZMW:Zambian Kwacha"},
{text: "ZWL", value: "ZWL:Zimbabwean Dollar},
]